#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $VIRTUAL_ENV/bin/activate
export PYTHONPATH="$PYTHONPATH:${OPENSHIFT_REPO_DIR}libs"

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/zosiaproject/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/zosiaproject/manage.py migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/zosiaproject/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/zosiaproject/manage.py collectstatic --noinput
