#!/bin/bash
date >> ${OPENSHIFT_DATA_DIR}/backup.log

BACKUP_DIR=${OPENSHIFT_DATA_DIR}/backups

python ${OPENSHIFT_REPO_DIR}/wsgi/zosiaproject/manage.py dbbackup -z -c

LAST_BACKUP=${BACKUP_DIR}/$(ls -t ${BACKUP_DIR} | head -n 1)
RECIPIENT=${DBBACKUP_EMAIL_RECIPIENT}

python <<EOF
from django.core.mail import EmailMessage

subject, from_email, to = 'backup', 'admin@zosia.org', '${RECIPIENT}'
text_content = 'This is database snapshot.'
msg = EmailMessage(subject, text_content, from_email, [to])
msg.attach_file("${LAST_BACKUP}")
msg.send()
EOF

echo '  email sent' >> ${OPENSHIFT_DATA_DIR}/backup.log
