#!/usr/bin/env python

import os
import sys

os.environ['DJANGO_SETTINGS_MODULE'] = 'zosiaproject.settings'
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'zosiaproject'))
os.environ['PYTHON_EGG_CACHE'] = os.path.join(os.environ['VIRTUAL_ENV'], 'lib', 'python3.3', 'site-packages')

import django.core.wsgi
application = django.core.wsgi.get_wsgi_application()
